# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ksw < Formula
  desc "Switch Kubeconfig context in new shell"
  homepage "https://github.com/chickenzord/ksw"
  version "0.7.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chickenzord/ksw/releases/download/v0.7.1/ksw_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "ce1494f1bb04e8ef13a552fba416edbd71ffeca564c48e2f295c6cddb711b0ba"

      def install
        if build.head?
          system "go", "build", *std_go_args(ldflags: "-s -w -X main.Version=0.7.1 -X main.GitCommit=72a922e236ae8f701fbd3cd303a45556cd7fca2f -X main.BuildDate=2025-12-23T06:09:49Z"), "."
        else
          bin.install "ksw"
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chickenzord/ksw/releases/download/v0.7.1/ksw_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "4e4bc84235598e3c7967bf381cae12c9a9823694e5aa7fda01bc3f19779e0e59"

      def install
        if build.head?
          system "go", "build", *std_go_args(ldflags: "-s -w -X main.Version=0.7.1 -X main.GitCommit=72a922e236ae8f701fbd3cd303a45556cd7fca2f -X main.BuildDate=2025-12-23T06:09:49Z"), "."
        else
          bin.install "ksw"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chickenzord/ksw/releases/download/v0.7.1/ksw_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "439807b6a440e598a478706e9459d31406df9d42b2587ff69f108cac2e68449c"
      def install
        if build.head?
          system "go", "build", *std_go_args(ldflags: "-s -w -X main.Version=0.7.1 -X main.GitCommit=72a922e236ae8f701fbd3cd303a45556cd7fca2f -X main.BuildDate=2025-12-23T06:09:49Z"), "."
        else
          bin.install "ksw"
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chickenzord/ksw/releases/download/v0.7.1/ksw_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "43b54d3b3155fe1697e24107af754d024a01fafa74f82d933897b19f22f93761"
      def install
        if build.head?
          system "go", "build", *std_go_args(ldflags: "-s -w -X main.Version=0.7.1 -X main.GitCommit=72a922e236ae8f701fbd3cd303a45556cd7fca2f -X main.BuildDate=2025-12-23T06:09:49Z"), "."
        else
          bin.install "ksw"
        end
      end
    end
  end

  head do
    url "https://github.com/chickenzord/ksw.git", branch: "main"
    depends_on "go" => :build
  end
end
