# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LinkdingMcp < Formula
  desc "Model Context Protocol server for Linkding bookmark manager"
  homepage "https://github.com/chickenzord/linkding-mcp"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chickenzord/linkding-mcp/releases/download/v0.1.6/linkding-mcp_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "b42e0fcf95a57d04c50f2042afd0bb48667c23ca024f5e22dcafbc4a3428882b"

      def install
        if build.head?
          system "go", "build", *std_go_args(ldflags: "-s -w -X github.com/chickenzord/linkding-mcp/internal/version.Version=0.1.6 -X github.com/chickenzord/linkding-mcp/internal/version.GitCommit=38d8849830f0dc0c25f7597666f2309c1ca27cb9 -X github.com/chickenzord/linkding-mcp/internal/version.BuildDate=2025-09-08T11:18:29Z"), "./cmd/linkding-mcp"
        else
          bin.install "linkding-mcp"
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chickenzord/linkding-mcp/releases/download/v0.1.6/linkding-mcp_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "4e06d3bebc0f530be1f0d0d2f80aff3b8009521d91e89606f912c7a791fe5770"

      def install
        if build.head?
          system "go", "build", *std_go_args(ldflags: "-s -w -X github.com/chickenzord/linkding-mcp/internal/version.Version=0.1.6 -X github.com/chickenzord/linkding-mcp/internal/version.GitCommit=38d8849830f0dc0c25f7597666f2309c1ca27cb9 -X github.com/chickenzord/linkding-mcp/internal/version.BuildDate=2025-09-08T11:18:29Z"), "./cmd/linkding-mcp"
        else
          bin.install "linkding-mcp"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chickenzord/linkding-mcp/releases/download/v0.1.6/linkding-mcp_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "bf497c18d919db877e2055bc30bb6829e1eefde0b2ef2a534da480609de2f609"
      def install
        if build.head?
          system "go", "build", *std_go_args(ldflags: "-s -w -X github.com/chickenzord/linkding-mcp/internal/version.Version=0.1.6 -X github.com/chickenzord/linkding-mcp/internal/version.GitCommit=38d8849830f0dc0c25f7597666f2309c1ca27cb9 -X github.com/chickenzord/linkding-mcp/internal/version.BuildDate=2025-09-08T11:18:29Z"), "./cmd/linkding-mcp"
        else
          bin.install "linkding-mcp"
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chickenzord/linkding-mcp/releases/download/v0.1.6/linkding-mcp_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "a0cf05e4af4ffac28cba48d577f532ab6bc6bf389b7467d4111cd0f2244bdd1b"
      def install
        if build.head?
          system "go", "build", *std_go_args(ldflags: "-s -w -X github.com/chickenzord/linkding-mcp/internal/version.Version=0.1.6 -X github.com/chickenzord/linkding-mcp/internal/version.GitCommit=38d8849830f0dc0c25f7597666f2309c1ca27cb9 -X github.com/chickenzord/linkding-mcp/internal/version.BuildDate=2025-09-08T11:18:29Z"), "./cmd/linkding-mcp"
        else
          bin.install "linkding-mcp"
        end
      end
    end
  end

  head do
    url "https://github.com/chickenzord/linkding-mcp.git", branch: "main"
    depends_on "go" => :build
  end
end
