# This file was generated by GoReleaser. DO NOT EDIT.
cask "linkding-cli" do
  name "linkding-cli"
  desc "CLI for any self-hosted linkding bookmark manager instance"
  homepage "https://github.com/chickenzord/linkding-cli"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "linkding-cli"

  on_macos do
    on_intel do
      url "https://github.com/chickenzord/linkding-cli/releases/download/v#{version}/linkding-cli_Darwin_x86_64.tar.gz"
      sha256 "494283ea76c9b77a01beacd85f5d38fcf8c69069b3e6db59187834671f69b26a"
    end
    on_arm do
      url "https://github.com/chickenzord/linkding-cli/releases/download/v#{version}/linkding-cli_Darwin_arm64.tar.gz"
      sha256 "14f3c9cba71413bfb577d7a4ec0ed23ce403a035a3c4e86114be9c5d46083db8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/chickenzord/linkding-cli/releases/download/v#{version}/linkding-cli_Linux_x86_64.tar.gz"
      sha256 "a9703cfc4f8bfa070061ab5842298bf8612800506f25411a1ef0939caaef7bdc"
    end
    on_arm do
      url "https://github.com/chickenzord/linkding-cli/releases/download/v#{version}/linkding-cli_Linux_arm64.tar.gz"
      sha256 "daba587f20eba855713c1d662e693923b7bd4de5aa6e3af4b6531fdb7afab8a3"
    end
  end

  # No zap stanza required
end
