# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Submail < Formula
  desc "A virtual inbox router for AI agents."
  homepage "https://github.com/chickenzord/submail"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chickenzord/submail/releases/download/v0.1.0/submail_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "482d25fe3b024b593d631de73b6b102b189e8bbc715da9dd631c3d7c950e9e2b"

      define_method(:install) do
        if build.head?
          system "go", "build", *std_go_args(ldflags: "-s -w -X github.com/chickenzord/submail/internal/version.Version=0.1.0 -X github.com/chickenzord/submail/internal/version.GitCommit=4be44c8d5eafbe99e2097f9b5ce886899018759d -X github.com/chickenzord/submail/internal/version.BuildDate=2026-03-17T19:14:32Z"), "./cmd/submail"
        else
          bin.install "submail"
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chickenzord/submail/releases/download/v0.1.0/submail_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "4d1b566403d54e618f86e7828cfa7a2bc5e1bc48c94da5ff3dc837d2b933fb66"

      define_method(:install) do
        if build.head?
          system "go", "build", *std_go_args(ldflags: "-s -w -X github.com/chickenzord/submail/internal/version.Version=0.1.0 -X github.com/chickenzord/submail/internal/version.GitCommit=4be44c8d5eafbe99e2097f9b5ce886899018759d -X github.com/chickenzord/submail/internal/version.BuildDate=2026-03-17T19:14:32Z"), "./cmd/submail"
        else
          bin.install "submail"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chickenzord/submail/releases/download/v0.1.0/submail_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "6f1ba3ac2fe5b28fe19577a25648cb95da6d7c1f403ead87896c4ff718a5a15a"
      define_method(:install) do
        if build.head?
          system "go", "build", *std_go_args(ldflags: "-s -w -X github.com/chickenzord/submail/internal/version.Version=0.1.0 -X github.com/chickenzord/submail/internal/version.GitCommit=4be44c8d5eafbe99e2097f9b5ce886899018759d -X github.com/chickenzord/submail/internal/version.BuildDate=2026-03-17T19:14:32Z"), "./cmd/submail"
        else
          bin.install "submail"
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chickenzord/submail/releases/download/v0.1.0/submail_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "460ea515f772fd3b64919fd7ae3b5c1989954b9b6cacf94ec84cabeee89dde86"
      define_method(:install) do
        if build.head?
          system "go", "build", *std_go_args(ldflags: "-s -w -X github.com/chickenzord/submail/internal/version.Version=0.1.0 -X github.com/chickenzord/submail/internal/version.GitCommit=4be44c8d5eafbe99e2097f9b5ce886899018759d -X github.com/chickenzord/submail/internal/version.BuildDate=2026-03-17T19:14:32Z"), "./cmd/submail"
        else
          bin.install "submail"
        end
      end
    end
  end

  head do
    url "https://github.com/chickenzord/submail.git", branch: "main"
    depends_on "go" => :build
  end
end
